adding quota support

diff --git a/src/run-it b/src/run-it
--- a/src/run-it
+++ b/src/run-it
@@ -22,4 +22,6 @@ then
         -p1000 2>&1 | tee out-c
 
 else
+    echo 'Invalid arguments'
+    exit 1
 fi
